-- Auto-generated by .githooks/pre-commit on every commit - do not edit by hand.
-- Structure only, plus the durable user_groups / user_group_rights seed rows
-- (see markdown/user_rights.txt). No user accounts, no other data.

--
-- PostgreSQL database dump
--

\restrict We9AepQpavyXKac3gKsTLWzTg8bKLjk0TTIUOGFwjfEMVGL7p9FzqqcAEcIebZV

-- Dumped from database version 14.24 (Homebrew)
-- Dumped by pg_dump version 14.24 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- Name: log_level; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.log_level AS ENUM (
    'trace',
    'debug',
    'info',
    'warn',
    'error',
    'fatal',
    'success'
);


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Change NEW.updated_at to NEW.updated
    NEW.updated := NOW(); 
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: access_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_log (
    id bigint NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    method character varying(8),
    path text,
    status integer,
    duration_ms double precision,
    user_id integer,
    session_id character varying(128),
    ip character varying(64),
    user_agent text,
    module character varying(64),
    action character varying(64),
    blocked boolean DEFAULT false NOT NULL,
    denied_reason character varying(32),
    country character varying(255)
);


--
-- Name: access_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.access_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: access_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.access_log_id_seq OWNED BY public.access_log.id;


--
-- Name: access_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_rule (
    id integer NOT NULL,
    cidr character varying(64),
    action character varying(8) DEFAULT 'deny'::character varying NOT NULL,
    note character varying(255),
    enabled boolean DEFAULT true NOT NULL,
    priority integer DEFAULT 100 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_agent text,
    firewall boolean DEFAULT false
);


--
-- Name: access_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.access_rule_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: access_rule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.access_rule_id_seq OWNED BY public.access_rule.id;


--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id integer DEFAULT nextval('public.comments_id_seq'::regclass) NOT NULL,
    uuid character varying(255) DEFAULT public.uuid_generate_v4() NOT NULL,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now(),
    created_by integer,
    access integer DEFAULT 0,
    module_id character varying(255) NOT NULL,
    row_id integer NOT NULL,
    body text NOT NULL
);


--
-- Name: config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.config (
    id bigint NOT NULL,
    scope text NOT NULL,
    scope_id bigint DEFAULT 0,
    theme text,
    date_format text,
    created timestamp with time zone DEFAULT now(),
    created_by bigint,
    access integer DEFAULT 0,
    updated timestamp with time zone DEFAULT now() NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4(),
    CONSTRAINT config_scope_check CHECK ((scope = ANY (ARRAY['global'::text, 'group'::text, 'user'::text])))
);


--
-- Name: config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: config_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.config_id_seq OWNED BY public.config.id;


--
-- Name: contact_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_messages (
    id bigint NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(120) NOT NULL,
    email character varying(200) NOT NULL,
    subject character varying(200),
    message text NOT NULL,
    handled boolean DEFAULT false NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    updated timestamp with time zone DEFAULT now() NOT NULL,
    access integer DEFAULT 0 NOT NULL,
    created_by integer
);


--
-- Name: contact_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.contact_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: contact_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.contact_messages_id_seq OWNED BY public.contact_messages.id;


--
-- Name: deletion_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.deletion_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: deletion_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deletion_requests (
    id integer DEFAULT nextval('public.deletion_requests_id_seq'::regclass) NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now(),
    created_by integer,
    access integer DEFAULT 0,
    email character varying(255) NOT NULL,
    user_id integer,
    reason character varying(255),
    note text,
    handled boolean DEFAULT false
);


--
-- Name: external_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.external_config (
    id integer NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now(),
    created_by integer,
    access integer DEFAULT 0,
    app_module text NOT NULL,
    provider text NOT NULL,
    group_id integer NOT NULL,
    related_modules jsonb
);


--
-- Name: external_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.external_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: external_config_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.external_config_id_seq OWNED BY public.external_config.id;


--
-- Name: friend_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.friend_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: friend_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.friend_requests (
    id integer DEFAULT nextval('public.friend_requests_id_seq'::regclass) NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now(),
    created_by integer,
    access integer DEFAULT 0,
    requester_id integer NOT NULL,
    recipient_id integer NOT NULL,
    status character varying(255) NOT NULL
);


--
-- Name: friends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.friends (
    id bigint NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    requester_id integer NOT NULL,
    recipient_id integer NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    created_by integer,
    created timestamp with time zone DEFAULT now() NOT NULL,
    updated timestamp with time zone DEFAULT now() NOT NULL,
    access integer DEFAULT 0 NOT NULL,
    CONSTRAINT friends_not_self CHECK ((requester_id <> recipient_id)),
    CONSTRAINT friends_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'accepted'::character varying])::text[])))
);


--
-- Name: friends_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.friends_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: friends_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.friends_id_seq OWNED BY public.friends.id;


--
-- Name: images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images (
    id bigint NOT NULL,
    uuid text NOT NULL,
    module text,
    field text,
    record_id bigint,
    filename text,
    mime_type text,
    access integer DEFAULT 0 NOT NULL,
    data bytea NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer,
    metadata jsonb
);


--
-- Name: images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: images_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.images_id_seq OWNED BY public.images.id;


--
-- Name: integration_test_table_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.integration_test_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: integration_test_table; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.integration_test_table (
    id integer DEFAULT nextval('public.integration_test_table_id_seq'::regclass) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.likes (
    id bigint NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    module_id text NOT NULL,
    row_id bigint NOT NULL,
    user_id integer NOT NULL,
    value smallint NOT NULL,
    created_by integer,
    created timestamp with time zone DEFAULT now() NOT NULL,
    updated timestamp with time zone DEFAULT now() NOT NULL,
    access integer DEFAULT 0 NOT NULL,
    CONSTRAINT likes_value_check CHECK ((value = ANY (ARRAY[1, '-1'::integer])))
);


--
-- Name: likes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: likes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.likes_id_seq OWNED BY public.likes.id;


--
-- Name: logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.logs (
    id bigint NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    level public.log_level DEFAULT 'info'::public.log_level NOT NULL,
    type text,
    message text NOT NULL,
    module text,
    action text,
    method text,
    request_url text,
    ip_address character varying(60),
    event_id text,
    session_id text,
    error text,
    user_id bigint,
    status_code integer,
    duration_ms integer,
    source text
);


--
-- Name: logs_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.logs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.logs_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.message_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: message_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_log (
    id integer DEFAULT nextval('public.message_log_id_seq'::regclass) NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now(),
    created_by integer,
    access integer DEFAULT 0,
    sender_id integer NOT NULL,
    recipient_id integer NOT NULL,
    body text NOT NULL
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sender_id integer NOT NULL,
    recipient_id integer NOT NULL,
    body text NOT NULL,
    read_at timestamp with time zone,
    created_by integer,
    created timestamp with time zone DEFAULT now() NOT NULL,
    updated timestamp with time zone DEFAULT now() NOT NULL,
    access integer DEFAULT 0 NOT NULL
);


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.messages_id_seq OWNED BY public.messages.id;


--
-- Name: module_rights_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.module_rights_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: modules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.modules (
    id integer NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(40) NOT NULL
);


--
-- Name: modules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.modules_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: modules_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.modules_id_seq OWNED BY public.modules.id;


--
-- Name: papers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.papers (
    id bigint NOT NULL,
    uuid text NOT NULL,
    name text NOT NULL,
    password text,
    created_by bigint,
    users text DEFAULT '[]'::text NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    deleted boolean DEFAULT false,
    access integer,
    wrong_answers integer,
    timer integer,
    updated timestamp with time zone,
    hash text
);


--
-- Name: papers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.papers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    id integer NOT NULL,
    title text NOT NULL,
    content text,
    drive_url text,
    drive_id character varying(40),
    created timestamp without time zone DEFAULT now(),
    updated timestamp without time zone DEFAULT now(),
    images json,
    created_by integer,
    access integer,
    visible_users jsonb,
    visible_groups jsonb
);


--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: posts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.posts_id_seq OWNED BY public.posts.id;


--
-- Name: prooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.prooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: prooms_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.prooms_id_seq OWNED BY public.papers.id;


--
-- Name: test_table_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.test_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: test_table; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_table (
    id integer DEFAULT nextval('public.test_table_id_seq'::regclass) NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    created timestamp with time zone DEFAULT now(),
    is_active boolean DEFAULT true
);


--
-- Name: translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.translations (
    id integer DEFAULT nextval('public.translations_id_seq'::regclass) NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now(),
    created_by integer,
    access integer DEFAULT 0,
    key character varying(255) NOT NULL,
    locale character varying(255) NOT NULL,
    value text NOT NULL
);


--
-- Name: user_group_rights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_group_rights (
    id bigint NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    group_id integer NOT NULL,
    module text NOT NULL,
    modes integer DEFAULT 0 NOT NULL,
    access integer DEFAULT 0 NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    updated timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer,
    fields text,
    special_rights jsonb,
    filter_fields text
);


--
-- Name: user_group_rights_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_group_rights_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_group_rights_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_group_rights_id_seq OWNED BY public.user_group_rights.id;


--
-- Name: user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_groups (
    id integer NOT NULL,
    name character varying(40),
    is_admin boolean DEFAULT false NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4(),
    created timestamp with time zone DEFAULT now() NOT NULL,
    updated timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer,
    access integer,
    description character varying(400),
    active boolean
);


--
-- Name: user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_groups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_groups_id_seq OWNED BY public.user_groups.id;


--
-- Name: user_rights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_rights (
    id bigint NOT NULL,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id integer NOT NULL,
    module text NOT NULL,
    modes integer DEFAULT 0 NOT NULL,
    access integer DEFAULT 0 NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    updated timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer,
    fields text,
    special_rights jsonb,
    filter_fields text
);


--
-- Name: user_rights_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_rights_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_rights_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_rights_id_seq OWNED BY public.user_rights.id;


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_name character varying(50) NOT NULL,
    email character varying(60),
    auth_parent_hash text,
    auth_hash text,
    auth_by smallint,
    auth_session_expires timestamp with time zone,
    uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    id integer DEFAULT nextval('public.users_id_seq'::regclass),
    first_name character varying(50) NOT NULL,
    last_name character varying(60),
    image text,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    created_by integer,
    user_groups json,
    password_hash text,
    access integer,
    auth_provider character varying(20),
    auth_provider_id character varying(191),
    groups jsonb DEFAULT '[]'::jsonb NOT NULL
);


--
-- Name: words; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.words (
    id integer NOT NULL,
    uuid uuid NOT NULL,
    created_by integer NOT NULL,
    word character varying(50) NOT NULL,
    tries integer NOT NULL,
    success integer NOT NULL,
    failure integer NOT NULL,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now(),
    access integer DEFAULT 0,
    fail integer DEFAULT 0
);


--
-- Name: words_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.words_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: words_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.words_id_seq OWNED BY public.words.id;


--
-- Name: access_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_log ALTER COLUMN id SET DEFAULT nextval('public.access_log_id_seq'::regclass);


--
-- Name: access_rule id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_rule ALTER COLUMN id SET DEFAULT nextval('public.access_rule_id_seq'::regclass);


--
-- Name: config id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.config ALTER COLUMN id SET DEFAULT nextval('public.config_id_seq'::regclass);


--
-- Name: contact_messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_messages ALTER COLUMN id SET DEFAULT nextval('public.contact_messages_id_seq'::regclass);


--
-- Name: external_config id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_config ALTER COLUMN id SET DEFAULT nextval('public.external_config_id_seq'::regclass);


--
-- Name: friends id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friends ALTER COLUMN id SET DEFAULT nextval('public.friends_id_seq'::regclass);


--
-- Name: images id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images ALTER COLUMN id SET DEFAULT nextval('public.images_id_seq'::regclass);


--
-- Name: likes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likes ALTER COLUMN id SET DEFAULT nextval('public.likes_id_seq'::regclass);


--
-- Name: messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages ALTER COLUMN id SET DEFAULT nextval('public.messages_id_seq'::regclass);


--
-- Name: modules id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modules ALTER COLUMN id SET DEFAULT nextval('public.modules_id_seq'::regclass);


--
-- Name: papers id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.papers ALTER COLUMN id SET DEFAULT nextval('public.prooms_id_seq'::regclass);


--
-- Name: posts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts ALTER COLUMN id SET DEFAULT nextval('public.posts_id_seq'::regclass);


--
-- Name: user_group_rights id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_group_rights ALTER COLUMN id SET DEFAULT nextval('public.user_group_rights_id_seq'::regclass);


--
-- Name: user_groups id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_groups ALTER COLUMN id SET DEFAULT nextval('public.user_groups_id_seq'::regclass);


--
-- Name: user_rights id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_rights ALTER COLUMN id SET DEFAULT nextval('public.user_rights_id_seq'::regclass);


--
-- Name: words id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.words ALTER COLUMN id SET DEFAULT nextval('public.words_id_seq'::regclass);


--
-- Name: access_log access_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_log
    ADD CONSTRAINT access_log_pkey PRIMARY KEY (id);


--
-- Name: access_rule access_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_rule
    ADD CONSTRAINT access_rule_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: config config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.config
    ADD CONSTRAINT config_pkey PRIMARY KEY (id);


--
-- Name: config config_scope_scope_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.config
    ADD CONSTRAINT config_scope_scope_id_key UNIQUE (scope, scope_id);


--
-- Name: contact_messages contact_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_messages
    ADD CONSTRAINT contact_messages_pkey PRIMARY KEY (id);


--
-- Name: deletion_requests deletion_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deletion_requests
    ADD CONSTRAINT deletion_requests_pkey PRIMARY KEY (id);


--
-- Name: external_config external_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_config
    ADD CONSTRAINT external_config_pkey PRIMARY KEY (id);


--
-- Name: friend_requests friend_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friend_requests
    ADD CONSTRAINT friend_requests_pkey PRIMARY KEY (id);


--
-- Name: friends friends_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friends
    ADD CONSTRAINT friends_pkey PRIMARY KEY (id);


--
-- Name: modules id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modules
    ADD CONSTRAINT id PRIMARY KEY (id);


--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- Name: images images_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_uuid_key UNIQUE (uuid);


--
-- Name: integration_test_table integration_test_table_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integration_test_table
    ADD CONSTRAINT integration_test_table_pkey PRIMARY KEY (id);


--
-- Name: likes likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT likes_pkey PRIMARY KEY (id);


--
-- Name: logs logs_pkey1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT logs_pkey1 PRIMARY KEY (id);


--
-- Name: message_log message_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_log
    ADD CONSTRAINT message_log_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (uuid);


--
-- Name: papers prooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.papers
    ADD CONSTRAINT prooms_pkey PRIMARY KEY (id);


--
-- Name: papers prooms_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.papers
    ADD CONSTRAINT prooms_uuid_key UNIQUE (uuid);


--
-- Name: test_table test_table_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_table
    ADD CONSTRAINT test_table_pkey PRIMARY KEY (id);


--
-- Name: translations translations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.translations
    ADD CONSTRAINT translations_pkey PRIMARY KEY (id);


--
-- Name: user_group_rights user_group_rights_group_module_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_group_rights
    ADD CONSTRAINT user_group_rights_group_module_key UNIQUE (group_id, module);


--
-- Name: user_group_rights user_group_rights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_group_rights
    ADD CONSTRAINT user_group_rights_pkey PRIMARY KEY (id);


--
-- Name: user_groups user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT user_groups_pkey PRIMARY KEY (id);


--
-- Name: user_rights user_rights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_rights
    ADD CONSTRAINT user_rights_pkey PRIMARY KEY (id);


--
-- Name: user_rights user_rights_user_module_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_rights
    ADD CONSTRAINT user_rights_user_module_key UNIQUE (user_id, module);


--
-- Name: users users_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_id_key UNIQUE (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (uuid);


--
-- Name: words words_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.words
    ADD CONSTRAINT words_pkey PRIMARY KEY (id);


--
-- Name: access_log_blocked_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX access_log_blocked_idx ON public.access_log USING btree (blocked) WHERE blocked;


--
-- Name: access_log_ip_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX access_log_ip_idx ON public.access_log USING btree (ip);


--
-- Name: access_log_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX access_log_status_idx ON public.access_log USING btree (status);


--
-- Name: access_log_ts_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX access_log_ts_idx ON public.access_log USING btree (ts DESC);


--
-- Name: access_rule_order_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX access_rule_order_idx ON public.access_rule USING btree (enabled, priority);


--
-- Name: config_lookup_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX config_lookup_idx ON public.config USING btree (scope, scope_id);


--
-- Name: idx_comments_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_target ON public.comments USING btree (module_id, row_id);


--
-- Name: idx_external_config_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_external_config_provider ON public.external_config USING btree (provider);


--
-- Name: idx_friends_pair; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_friends_pair ON public.friends USING btree (LEAST(requester_id, recipient_id), GREATEST(requester_id, recipient_id));


--
-- Name: idx_friends_recipient; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_friends_recipient ON public.friends USING btree (recipient_id, status);


--
-- Name: idx_likes_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_likes_target ON public.likes USING btree (module_id, row_id);


--
-- Name: idx_likes_target_user; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_likes_target_user ON public.likes USING btree (module_id, row_id, user_id);


--
-- Name: idx_messages_recipient_unread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_recipient_unread ON public.messages USING btree (recipient_id, sender_id) WHERE (read_at IS NULL);


--
-- Name: idx_messages_sender_recipient; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_sender_recipient ON public.messages USING btree (sender_id, recipient_id, created);


--
-- Name: idx_translations_key_locale; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_translations_key_locale ON public.translations USING btree (key, locale);


--
-- Name: idx_ugr_group; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ugr_group ON public.user_group_rights USING btree (group_id);


--
-- Name: idx_ur_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ur_user ON public.user_rights USING btree (user_id);


--
-- Name: images_metadata_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX images_metadata_gin ON public.images USING gin (metadata);


--
-- Name: papers_hash_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX papers_hash_idx ON public.papers USING btree (hash);


--
-- Name: prooms_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX prooms_created_idx ON public.papers USING btree (created);


--
-- Name: users_provider_ident; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_provider_ident ON public.users USING btree (auth_provider, auth_provider_id) WHERE ((auth_provider IS NOT NULL) AND (auth_provider_id IS NOT NULL));


--
-- Name: posts trg_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON public.posts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: users trg_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: user_group_rights user_group_rights_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_group_rights
    ADD CONSTRAINT user_group_rights_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.user_groups(id);


--
-- Name: user_rights user_rights_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_rights
    ADD CONSTRAINT user_rights_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: words words_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.words
    ADD CONSTRAINT words_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict We9AepQpavyXKac3gKsTLWzTg8bKLjk0TTIUOGFwjfEMVGL7p9FzqqcAEcIebZV


-- Durable role/rights seed.
--
-- PostgreSQL database dump
--

\restrict ThYKIYihtWEtKoBZHw1VZCp06Yo63leCgp6TclPU2jEAaOTj7gt5db1cDwCnNxS

-- Dumped from database version 14.24 (Homebrew)
-- Dumped by pg_dump version 14.24 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.user_groups (id, name, is_admin, uuid, created, updated, created_by, access, description, active) VALUES (0, 'admins', true, 'b734cc6c-a870-4999-86ef-22a344bc42c1', '2026-08-17 16:30:51.028925-07', '2026-08-17 16:31:23.775001-07', 1, NULL, NULL, true);
INSERT INTO public.user_groups (id, name, is_admin, uuid, created, updated, created_by, access, description, active) VALUES (1, 'guests', false, '7e3ae98e-a029-4847-89cf-96e1625d6b0d', '2026-08-17 16:30:51.028925-07', '2026-08-17 16:31:23.775001-07', 1, NULL, NULL, true);
INSERT INTO public.user_groups (id, name, is_admin, uuid, created, updated, created_by, access, description, active) VALUES (2, 'users', false, '5ef17269-fdbe-49ef-bc5d-1308a044739a', '2026-08-17 16:30:51.028925-07', '2026-08-17 16:31:23.775001-07', 1, NULL, NULL, true);
INSERT INTO public.user_groups (id, name, is_admin, uuid, created, updated, created_by, access, description, active) VALUES (4, 'words_app', false, '6bc37b13-09ce-4f9d-9196-f01294114c97', '2026-09-13 23:13:56.606369-07', '2026-09-13 23:13:56.606369-07', 1, NULL, 'words app users', true);
INSERT INTO public.user_groups (id, name, is_admin, uuid, created, updated, created_by, access, description, active) VALUES (5, 'papers_app', false, '83132280-8154-40dd-bf68-bd26fcb1bf44', '2026-09-13 23:15:12.880771-07', '2026-09-13 23:15:12.880771-07', 1, NULL, 'papers app users', true);


--
-- Data for Name: user_group_rights; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (14, '6f9a868e-eade-4185-bc33-27eaca7128ef', 1, 'images', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (4, '2cbc069b-cf7a-43ad-877e-9eb532447f83', 0, 'access_log', 31, 0, '2026-09-10 12:16:00.512703-07', '2026-09-10 12:16:00.512703-07', 1, '{"action":["list","view","create","edit","delete"],"blocked":["list","view","create","edit","delete"],"country":["list","view","create","edit","delete"],"denied_reason":["list","view","create","edit","delete"],"duration_ms":["list","view","create","edit","delete"],"ip":["list","view","create","edit","delete"],"method":["list","view","create","edit","delete"],"module":["list","view","create","edit","delete"],"path":["list","view","create","edit","delete"],"session_id":["list","view","create","edit","delete"],"status":["list","view","create","edit","delete"],"ts":["list","view","create","edit","delete"],"user_agent":["list","view","create","edit","delete"],"user_id":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (7, '26816699-2332-4dce-a3f9-a58b5439fde2', 1, 'users', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (8, '77cbc8f1-4f4c-4f9a-8307-27f4872b5809', 1, 'words', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (9, 'e75d7c7a-b0ee-443f-ba0b-be62fbe9e140', 1, 'user_groups', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (10, 'b03fb7a0-49bb-46ea-99ae-b70787527efd', 1, 'user_group_rights', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (11, '330988bd-88ff-4437-8bcd-49d73daf04a9', 1, 'user_rights', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (12, 'dced2c9f-9ca2-43a1-9eaa-6e248cdc2f04', 1, 'access_log', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (13, 'd922067e-bb0a-46aa-9f8f-58c1acbc210a', 1, 'access_rule', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (15, '33d66a14-4517-44f5-af75-1e8114b8b644', 1, 'comments', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (16, '6f03a225-50c1-4bcd-81e7-6a30b1caca62', 1, 'likes', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (17, '29c95d15-45b8-40fa-8611-1af14a47b848', 1, 'message_log', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (18, '26e18f43-3306-4221-a5b9-09f9ae5b75ea', 1, 'friend_requests', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (19, '569ca18b-c1f7-4f71-8b92-f794a5fc7884', 1, 'contact_messages', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (20, '09485f55-ceb6-44e1-bf1e-ba90fd0e57ae', 1, 'deletion_requests', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (21, '895dbfc6-b9f0-4040-848c-e45ffc386032', 1, 'translations', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (22, 'a8404d43-ff56-498e-a3d3-5a46251ea045', 1, 'config', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (23, 'a3dd0a76-ef94-4741-9931-4bd0ed093a77', 1, 'papers', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"deleted":["list","view","create","edit","delete"],"has_password":["list","view","create","edit","delete"],"hash":["list","view","create","edit","delete"],"name":["list","view","create","edit","delete"],"password":["list","view","create","edit","delete"],"timer":["list","view","create","edit","delete"],"users":["list","view","create","edit","delete"],"wrong_answers":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (24, 'ca2155e9-34fc-4ae2-bd09-621f5858aa44', 2, 'users', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (25, '22a75b19-5f38-4772-9e20-236433bd685a', 2, 'words', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (26, 'ddc61d39-3b88-4816-b0d2-ec984006ec8a', 2, 'user_groups', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (27, '0ab6f3d6-0691-4d1a-a219-adb746316129', 2, 'user_group_rights', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (28, 'efd8333c-e00a-4494-b792-5726378beb19', 2, 'user_rights', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (29, 'c225f7e4-93ad-41ea-8cc9-e64ead995106', 2, 'access_log', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (30, 'ce5fceaa-2bdc-4bf4-a77c-44dc7b7c8746', 2, 'access_rule', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (6, 'd1bf88e8-a71b-4568-8fe0-87ea0c78013d', 2, 'posts', 47, 0, '2026-09-13 16:02:57.009316-07', '2026-09-13 16:02:57.009316-07', NULL, '{"access":["list","view","create","edit"],"author":["list","view","create","edit"],"comments_count":["list","view","create","edit"],"content":["list","view","create","edit"],"created":["list","view","create","edit"],"created_by":["list","view","create","edit"],"images":["list","view","create","edit"],"likes_count":["list","view","create","edit"],"title":["list","view","create","edit"],"updated":["list","view","create","edit"],"uuid":["list","view","create","edit"],"visible_groups":["list","view","create","edit"],"visible_users":["list","view","create","edit"]}', NULL, '["title"]');
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (5, 'b4909e04-7463-4c08-a9a0-3dc9ece45b48', 1, 'posts', 3, 0, '2026-09-13 16:02:57.009316-07', '2026-09-13 16:02:57.009316-07', NULL, '{"author":["list","view"],"comments_count":["list","view"],"content":["list","view"],"images":["list","view"],"likes_count":["list","view"],"title":["list","view"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (31, '918441fa-1169-4c22-af9b-4bffa6d3b106', 2, 'images', 3, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"field":["list","view"],"filename":["list","view"],"mime_type":["list","view"],"module":["list","view"],"preview":["list","view"],"record_id":["list","view"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (32, '26f5bdd2-096c-4abb-834a-2749886b3be9', 2, 'comments', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (33, 'da11c050-8e5b-40f0-9d99-7e31fce3ec26', 2, 'likes', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (34, '92654dbb-d9d6-4b89-a24a-ba0195e9b4a5', 2, 'message_log', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (35, '6a2f22e1-f655-4de1-b4b7-909105fbb8a7', 2, 'friend_requests', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (36, 'c427336d-6bab-491c-b563-c0cd15e3fe3c', 2, 'contact_messages', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (37, 'c114f821-62ea-4b50-b58a-5ee42d985f0d', 2, 'deletion_requests', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (38, '1f2c05f2-eae1-432e-98b6-86b76300ecb2', 2, 'translations', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (39, '8c8b9c53-dca7-4056-9551-e6cfe2a9f601', 2, 'config', 0, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (40, '07aadd3e-3346-41c2-bbca-a11de8b57bc2', 2, 'papers', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"deleted":["list","view","create","edit","delete"],"has_password":["list","view","create","edit","delete"],"hash":["list","view","create","edit","delete"],"name":["list","view","create","edit","delete"],"password":["list","view","create","edit","delete"],"timer":["list","view","create","edit","delete"],"users":["list","view","create","edit","delete"],"wrong_answers":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (41, '4ce53982-e8ee-4a96-920e-1688310e3a0a', 0, 'users', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"email":["list","view","create","edit","delete"],"first_name":["list","view","create","edit","delete"],"group":["list","view","create","edit","delete"],"groups":["list","view","create","edit","delete"],"image":["list","view","create","edit","delete"],"last_name":["list","view","create","edit","delete"],"user_name":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (43, 'caf92bf8-3f09-4de3-bc5f-d905be945234', 0, 'words', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"fail":["list","view","create","edit","delete"],"success":["list","view","create","edit","delete"],"translations":["list","view","create","edit","delete"],"tries":["list","view","create","edit","delete"],"win_rate":["list","view","create","edit","delete"],"word":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (44, 'cd021529-2c8d-4bcf-9ea8-0a35837da0f5', 0, 'user_groups', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"active":["list","view","create","edit","delete"],"description":["list","view","create","edit","delete"],"is_admin":["list","view","create","edit","delete"],"name":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (45, 'e8398de2-c858-4b03-85de-0d475f8f6df8', 0, 'user_group_rights', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"group_id":["list","view","create","edit","delete"],"module":["list","view","create","edit","delete"],"modes":["list","view","create","edit","delete"],"fields":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (46, '9bda5cff-3e55-4f36-8778-d090e822fdcb', 0, 'user_rights', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"user_id":["list","view","create","edit","delete"],"module":["list","view","create","edit","delete"],"modes":["list","view","create","edit","delete"],"fields":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (47, '2a55c71d-b462-4fc4-a6f4-6a29f016d390', 0, 'access_rule', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"action":["list","view","create","edit","delete"],"cidr":["list","view","create","edit","delete"],"enabled":["list","view","create","edit","delete"],"firewall":["list","view","create","edit","delete"],"note":["list","view","create","edit","delete"],"priority":["list","view","create","edit","delete"],"user_agent":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (48, '90fc228d-dd35-4a90-aec7-d76a3167421a', 0, 'images', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"field":["list","view","create","edit","delete"],"filename":["list","view","create","edit","delete"],"mime_type":["list","view","create","edit","delete"],"module":["list","view","create","edit","delete"],"preview":["list","view","create","edit","delete"],"record_id":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (49, 'e6c5f984-e508-4191-a451-7ef0329c2a5e', 0, 'comments', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"body":["list","view","create","edit","delete"],"module_id":["list","view","create","edit","delete"],"row_id":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (50, 'd936ae58-6de2-4dbf-84be-2c2c65bcbe3e', 0, 'likes', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"module_id":["list","view","create","edit","delete"],"row_id":["list","view","create","edit","delete"],"user_id":["list","view","create","edit","delete"],"value":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (51, '0bb0f7c0-7a97-4a56-b7d1-97607c187337', 0, 'message_log', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"body":["list","view","create","edit","delete"],"recipient_id":["list","view","create","edit","delete"],"sender_id":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (52, '2fa86210-b2a2-42f5-9f03-160a630c94cb', 0, 'friend_requests', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"recipient_id":["list","view","create","edit","delete"],"requester_id":["list","view","create","edit","delete"],"status":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (53, '7a43123f-b8a2-4568-9c24-e5c03c0f1b37', 0, 'contact_messages', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"email":["list","view","create","edit","delete"],"handled":["list","view","create","edit","delete"],"message":["list","view","create","edit","delete"],"name":["list","view","create","edit","delete"],"subject":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (54, '0707781b-71b6-4d4f-9954-3c0178c97b71', 0, 'deletion_requests', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"email":["list","view","create","edit","delete"],"handled":["list","view","create","edit","delete"],"note":["list","view","create","edit","delete"],"reason":["list","view","create","edit","delete"],"user_id":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (55, '3a219ab9-4329-4d57-942e-7f1feacd2a54', 0, 'translations', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"key":["list","view","create","edit","delete"],"locale":["list","view","create","edit","delete"],"value":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (56, 'cc767e8a-64da-4f06-b8a7-c7eba0fbd9d8', 0, 'config', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"date_format":["list","view","create","edit","delete"],"scope_id":["list","view","create","edit","delete"],"scope":["list","view","create","edit","delete"],"theme":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (57, 'bf350f67-dadb-4307-8263-79a16b4914cb', 0, 'papers', 31, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"uuid":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"access":["list","view","create","edit","delete"],"deleted":["list","view","create","edit","delete"],"has_password":["list","view","create","edit","delete"],"hash":["list","view","create","edit","delete"],"name":["list","view","create","edit","delete"],"password":["list","view","create","edit","delete"],"timer":["list","view","create","edit","delete"],"users":["list","view","create","edit","delete"],"wrong_answers":["list","view","create","edit","delete"]}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (58, 'f90dd7c1-7437-43c4-b9c7-fe2313649411', 2, 'profile', 10, 0, '2026-09-14 21:23:29.760462-07', '2026-09-14 21:23:29.760462-07', NULL, '{}', NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (59, 'd17d5ddd-e785-4c5c-b032-44aaf0b69518', 4, 'words', 15, 0, '2026-09-17 14:29:08.134048-07', '2026-09-17 14:29:08.134048-07', NULL, NULL, NULL, NULL);
INSERT INTO public.user_group_rights (id, uuid, group_id, module, modes, access, created, updated, created_by, fields, special_rights, filter_fields) VALUES (42, 'bf7e70b9-1e36-4ea4-8673-466edccce0d9', 0, 'posts', 63, 0, '2026-09-14 21:15:25.118066-07', '2026-09-14 21:15:25.118066-07', NULL, '{"access":["list","view","create","edit","delete"],"author":["list","view","create","edit","delete"],"comments_count":["list","view","create","edit","delete"],"content":["list","view","create","edit","delete"],"created":["list","view","create","edit","delete"],"created_by":["list","view","create","edit","delete"],"images":["list","view","create","edit","delete"],"likes_count":["list","view","create","edit","delete"],"title":["list","view","create","edit","delete"],"updated":["list","view","create","edit","delete"],"uuid":["list","view","create","edit","delete"],"visible_groups":["list","view","create","edit","delete"],"visible_users":["list","view","create","edit","delete"]}', NULL, '["title","user","user_group","created_from","created_to"]');


--
-- Name: user_group_rights_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.user_group_rights_id_seq', 59, true);


--
-- Name: user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.user_groups_id_seq', 5, true);


--
-- PostgreSQL database dump complete
--

\unrestrict ThYKIYihtWEtKoBZHw1VZCp06Yo63leCgp6TclPU2jEAaOTj7gt5db1cDwCnNxS

