services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tls-rest
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "8443:8443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENV=production
    volumes:
      - /opt/workstation/certs/cert.pem:/app/.private/cert.pem:ro
      - /opt/workstation/certs/key.pem:/app/.private/key.pem:ro
      - /opt/workstation/.env:/app/.private/.env:ro
    networks:
      - workstation_infra_net

networks:
  workstation_infra_net:
    external: true