-- 2026.09.12 — translations: i18n strings keyed by (key, locale). Seeded in
-- English the first time a string is used at runtime; admins edit other
-- locales' rows here. The engine also auto-creates these columns from the
-- translations module fieldset; this file pins the types and uniqueness.
CREATE TABLE IF NOT EXISTS public.translations (
    id         bigserial   PRIMARY KEY,
    uuid       uuid        NOT NULL DEFAULT uuid_generate_v4(),
    key        text        NOT NULL,
    locale     varchar(8)  NOT NULL,
    value      text        NOT NULL,
    created_by integer,
    created    timestamptz NOT NULL DEFAULT now(),
    updated    timestamptz NOT NULL DEFAULT now(),
    access     integer     NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_translations_key_locale ON public.translations (key, locale);

-- Seed Russian text for every string already wired up to t() this pass. New
-- keys added later auto-seed their English default at runtime (see
-- translations.Resolve); admins add their Russian text through this module.
INSERT INTO public.translations (key, locale, value) VALUES
('Actions', 'ru', 'Действия'),
('Add a comment… (Markdown supported)', 'ru', 'Добавить комментарий… (поддерживается Markdown)'),
('Add row', 'ru', 'Добавить строку'),
('Admin actions console. Type', 'ru', 'Консоль администратора. Введите'),
('All fields', 'ru', 'Все поля'),
('Anonymous', 'ru', 'Аноним'),
('Any', 'ru', 'Любой'),
('Apply', 'ru', 'Применить'),
('Are you sure you want to delete this item?', 'ru', 'Вы уверены, что хотите удалить этот элемент?'),
('Authentication failed', 'ru', 'Ошибка аутентификации'),
('Awaiting Connection / Handshake...', 'ru', 'Ожидание соединения...'),
('Back', 'ru', 'Назад'),
('Back to List', 'ru', 'Назад к списку'),
('Browser Base64 Session Offer:', 'ru', 'Base64-предложение сессии браузера:'),
('Button', 'ru', 'Кнопка'),
('by', 'ru', 'от'),
('By', 'ru', 'Автор:'),
('Cancel', 'ru', 'Отмена'),
('characters', 'ru', 'символов'),
('Chat', 'ru', 'Чат'),
('Clear', 'ru', 'Очистить'),
('Click to view full text', 'ru', 'Нажмите, чтобы увидеть полный текст'),
('Close', 'ru', 'Закрыть'),
('Columns', 'ru', 'Столбцы'),
('comment', 'ru', 'комментарий'),
('Comment', 'ru', 'Комментарий'),
('Comments', 'ru', 'Комментарии'),
('Connection closed (admin session required, or scan finished).', 'ru', 'Соединение закрыто (требуется сеанс администратора или сканирование завершено).'),
('Console', 'ru', 'Консоль'),
('Contact', 'ru', 'Контакты'),
('Core competencies', 'ru', 'Ключевые компетенции'),
('Could not join the room.', 'ru', 'Не удалось присоединиться к комнате.'),
('Could not load comments.', 'ru', 'Не удалось загрузить комментарии.'),
('Could not post comment.', 'ru', 'Не удалось отправить комментарий.'),
('Create', 'ru', 'Создать'),
('Create account', 'ru', 'Создать аккаунт'),
('Create New Post', 'ru', 'Создать новый пост'),
('default', 'ru', 'по умолчанию'),
('Delete', 'ru', 'Удалить'),
('denied', 'ru', 'запрещено'),
('Dismiss', 'ru', 'Закрыть'),
('Drag nodes, scroll to zoom, hover to inspect', 'ru', 'Перетаскивайте узлы, прокручивайте для масштабирования, наводите для просмотра'),
('Edit', 'ru', 'Редактировать'),
('Edit Post', 'ru', 'Редактировать пост'),
('Email', 'ru', 'Эл. почта'),
('End game', 'ru', 'Завершить игру'),
('English — fluent, academic · Russian — native', 'ru', 'Английский — свободно, академический уровень · Русский — родной'),
('Enter', 'ru', 'Войти'),
('Enter JSON...', 'ru', 'Введите JSON...'),
('Enter your query here', 'ru', 'Введите запрос здесь'),
('error:', 'ru', 'ошибка:'),
('Establishing WebRTC handshake...', 'ru', 'Установка WebRTC-соединения...'),
('Experience', 'ru', 'Опыт работы'),
('Failed to delete post', 'ru', 'Не удалось удалить пост'),
('Failed to load', 'ru', 'Не удалось загрузить'),
('Failed to load form configuration:', 'ru', 'Не удалось загрузить конфигурацию формы:'),
('Failed to load list configuration:', 'ru', 'Не удалось загрузить конфигурацию списка:'),
('Failed to save post', 'ru', 'Не удалось сохранить пост'),
('Final scores', 'ru', 'Итоговые результаты'),
('for commands.', 'ru', 'для списка команд.'),
('for someone else', 'ru', 'для другого игрока'),
('format is invalid', 'ru', 'имеет неверный формат'),
('Golang Server SDP Status:', 'ru', 'Статус SDP сервера Golang:'),
('Have an account?', 'ru', 'Уже есть аккаунт?'),
('Home', 'ru', 'Главная'),
('Idle. Press “Run scan” to map the network.', 'ru', 'Ожидание. Нажмите «Запустить сканирование», чтобы построить карту сети.'),
('Image upload failed', 'ru', 'Не удалось загрузить изображение'),
('Initializing Network Mesh Engine...', 'ru', 'Инициализация движка сетевой топологии...'),
('Initializing network scanner...', 'ru', 'Инициализация сканера сети...'),
('Insert image at cursor', 'ru', 'Вставить изображение в курсор'),
('Invalid JSON', 'ru', 'Неверный JSON'),
('is required', 'ru', 'обязательно для заполнения'),
('Item details & metadata', 'ru', 'Сведения и метаданные записи'),
('Join', 'ru', 'Войти'),
('Join in a few seconds.', 'ru', 'Регистрация займёт всего пару секунд.'),
('Language', 'ru', 'Язык'),
('Languages', 'ru', 'Языки'),
('Live Network Mesh Graph', 'ru', 'Граф сети в реальном времени'),
('Live status:', 'ru', 'Текущий статус:'),
('Loading…', 'ru', 'Загрузка…'),
('Loading fieldset...', 'ru', 'Загрузка формы...'),
('Loading...', 'ru', 'Загрузка...'),
('Local Camera Feed (Input)', 'ru', 'Локальная камера (вход)'),
('log id:', 'ru', 'ID журнала:'),
('Logout', 'ru', 'Выйти'),
('Logs', 'ru', 'Журнал'),
('Message', 'ru', 'Сообщение'),
('must be a valid email address', 'ru', 'должно быть корректным адресом эл. почты'),
('must be a valid number', 'ru', 'должно быть корректным числом'),
('must be at least', 'ru', 'должно быть не менее'),
('must not exceed', 'ru', 'не должно превышать'),
('Name', 'ru', 'Имя'),
('Need an account?', 'ru', 'Нет аккаунта?'),
('Network Mapper', 'ru', 'Карта сети'),
('Next', 'ru', 'Далее'),
('No', 'ru', 'Нет'),
('No active games right now.', 'ru', 'Сейчас нет активных игр.'),
('No comments yet. Be the first.', 'ru', 'Пока нет комментариев. Будьте первым.'),
('No data available', 'ru', 'Нет данных'),
('No fieldset configuration available', 'ru', 'Конфигурация формы недоступна'),
('No images.', 'ru', 'Нет изображений.'),
('No list configuration available', 'ru', 'Конфигурация списка недоступна'),
('No messages yet.', 'ru', 'Пока нет сообщений.'),
('No output yet.', 'ru', 'Пока нет вывода.'),
('No posts yet.', 'ru', 'Пока нет постов.'),
('No rows.', 'ru', 'Нет строк.'),
('optional', 'ru', 'необязательно'),
('or', 'ru', 'или'),
('Password', 'ru', 'Пароль'),
('Password required', 'ru', 'Требуется пароль'),
('player', 'ru', 'игрок'),
('Player', 'ru', 'Игрок'),
('players', 'ru', 'игроков'),
('Please wait…', 'ru', 'Пожалуйста, подождите…'),
('Post comment', 'ru', 'Опубликовать комментарий'),
('Posts', 'ru', 'Посты'),
('Preview', 'ru', 'Просмотр'),
('Previous', 'ru', 'Назад'),
('Processed OpenCV Stream (WebRTC Output)', 'ru', 'Обработанный поток OpenCV (выход WebRTC)'),
('Query', 'ru', 'Запрос'),
('Register', 'ru', 'Зарегистрироваться'),
('remove', 'ru', 'удалить'),
('Remove row', 'ru', 'Удалить строку'),
('Reply', 'ru', 'Ответить'),
('Reply to', 'ru', 'Ответ для'),
('Required fields', 'ru', 'Обязательные поля'),
('Reset', 'ru', 'Сбросить'),
('Restart', 'ru', 'Начать заново'),
('Room', 'ru', 'Комната'),
('Run', 'ru', 'Выполнить'),
('Run scan', 'ru', 'Запустить сканирование'),
('Save', 'ru', 'Сохранить'),
('Saved.', 'ru', 'Сохранено.'),
('Saving…', 'ru', 'Сохранение…'),
('Say something…', 'ru', 'Напишите что-нибудь…'),
('Scan complete.', 'ru', 'Сканирование завершено.'),
('Scanning…', 'ru', 'Сканирование…'),
('Scores so far', 'ru', 'Текущие результаты'),
('scroll to upgrade', 'ru', 'прокрутите для обновления'),
('Select all', 'ru', 'Выбрать все'),
('Select OpenCV Processing Filter:', 'ru', 'Выберите фильтр обработки OpenCV:'),
('Select row', 'ru', 'Выбрать строку'),
('selected item(s)?', 'ru', 'выбранных элементов?'),
('Send', 'ru', 'Отправить'),
('Send message', 'ru', 'Отправить сообщение'),
('Send Query', 'ru', 'Отправить запрос'),
('Sending…', 'ru', 'Отправка…'),
('Set', 'ru', 'Установить'),
('Sign in', 'ru', 'Войти'),
('So we can reply to you.', 'ru', 'Чтобы мы могли вам ответить.'),
('Something went wrong:', 'ru', 'Что-то пошло не так:'),
('Sorry — the message could not be sent. Please try again later.', 'ru', 'Извините — сообщение не удалось отправить. Попробуйте позже.'),
('Start', 'ru', 'Начать'),
('STREAM ACTIVE (ID:', 'ru', 'ПОТОК АКТИВЕН (ID:'),
('Subject', 'ru', 'Тема'),
('Summary', 'ru', 'Резюме'),
('Switch between this module''s custom layout and the system default', 'ru', 'Переключение между пользовательским макетом модуля и системным по умолчанию'),
('system', 'ru', 'системный'),
('system ready', 'ru', 'система готова'),
('Thanks — your message has been received. We''ll get back to you at the address you provided.', 'ru', 'Спасибо — ваше сообщение получено. Мы свяжемся с вами по указанному адресу.'),
('This game is password-protected.', 'ru', 'Эта игра защищена паролем.'),
('This is data', 'ru', 'Это страница данных'),
('This is money page', 'ru', 'Это страница финансов'),
('This is OpenCV webrtc to gocv implementation', 'ru', 'Это реализация OpenCV WebRTC → GoCV'),
('This is users', 'ru', 'Это пользователи'),
('This table has no columns configured.', 'ru', 'В этой таблице не настроены столбцы.'),
('Unknown', 'ru', 'Неизвестно'),
('Untitled', 'ru', 'Без названия'),
('Upload image', 'ru', 'Загрузить изображение'),
('Upload images', 'ru', 'Загрузить изображения'),
('Uploading...', 'ru', 'Загрузка...'),
('Use the form below to get in touch. Your message is delivered privately — no email address is published on this site.', 'ru', 'Используйте форму ниже, чтобы связаться с нами. Ваше сообщение доставляется конфиденциально — на сайте не публикуется ни один адрес эл. почты.'),
('Username', 'ru', 'Имя пользователя'),
('Valid JSON', 'ru', 'JSON корректен'),
('View', 'ru', 'Просмотр'),
('View Post', 'ru', 'Просмотр поста'),
('Waiting for players…', 'ru', 'Ожидание игроков…'),
('WebRTC Hardware Stream-In / Stream-Out Pipeline', 'ru', 'Конвейер WebRTC: приём и вывод потока'),
('Welcome back.', 'ru', 'С возвращением.'),
('Word guessed', 'ru', 'Слово угадано'),
('Word set', 'ru', 'Слово задано'),
('Write', 'ru', 'Написать'),
('Write in Markdown: **bold**, _italic_, [link](url), `code`, - lists…', 'ru', 'Пишите в формате Markdown: **жирный**, _курсив_, [ссылка](url), `код`, - списки…'),
('Write using BBCode: [b]bold[/b], [i]italic[/i], ...', 'ru', 'Используйте BBCode: [b]жирный[/b], [i]курсив[/i], ...'),
('Wrong', 'ru', 'Неверно'),
('Yes', 'ru', 'Да'),
('You', 'ru', 'Вы'),
('Your name', 'ru', 'Ваше имя'),
('Your word', 'ru', 'Ваше слово')
ON CONFLICT (key, locale) DO NOTHING;

-- Module names, submenu groups, and common field labels (spot-checked
-- against go/engine/modules, go/modules, go/engine/pages, go/pages).
INSERT INTO public.translations (key, locale, value) VALUES
('Action', 'ru', 'Действие'),
('Blocked', 'ru', 'Заблокировано'),
('Blocked only', 'ru', 'Только заблокированные'),
('Denied reason', 'ru', 'Причина отказа'),
('Duration (ms)', 'ru', 'Длительность (мс)'),
('Enabled', 'ru', 'Включено'),
('Error', 'ru', 'Ошибка'),
('Event ID', 'ru', 'ID события'),
('Field', 'ru', 'Поле'),
('Filename', 'ru', 'Имя файла'),
('From', 'ru', 'От'),
('Handled', 'ru', 'Обработано'),
('IP', 'ru', 'IP'),
('IP/CIDR', 'ru', 'IP/CIDR'),
('Key', 'ru', 'Ключ'),
('Level', 'ru', 'Уровень'),
('List', 'ru', 'Список'),
('Locale', 'ru', 'Локаль'),
('Method', 'ru', 'Метод'),
('Module', 'ru', 'Модуль'),
('Name', 'ru', 'Имя'),
('Note', 'ru', 'Заметка'),
('Path', 'ru', 'Путь'),
('Reason', 'ru', 'Причина'),
('Record', 'ru', 'Запись'),
('Row', 'ru', 'Строка'),
('Session', 'ru', 'Сессия'),
('Status', 'ru', 'Статус'),
('Time', 'ru', 'Время'),
('To', 'ru', 'Кому'),
('Type', 'ru', 'Тип'),
('URL', 'ru', 'URL'),
('User', 'ru', 'Пользователь'),
('User agent', 'ru', 'Юзер-агент'),
('User ID', 'ru', 'ID пользователя'),
('Value', 'ru', 'Значение'),
('Access Rules', 'ru', 'Правила доступа'),
('Images', 'ru', 'Изображения'),
('Config', 'ru', 'Настройки'),
('Group Rights', 'ru', 'Права групп'),
('User Rights', 'ru', 'Права пользователей'),
('Users', 'ru', 'Пользователи'),
('Access Log', 'ru', 'Журнал доступа'),
('Contact Messages', 'ru', 'Контактные сообщения'),
('Deletion Requests', 'ru', 'Запросы на удаление'),
('Translations', 'ru', 'Переводы'),
('User Groups', 'ru', 'Группы пользователей'),
('Words', 'ru', 'Слова'),
('Login', 'ru', 'Вход'),
('Profile', 'ru', 'Профиль'),
('Money', 'ru', 'Деньги'),
('Delete Account', 'ru', 'Удаление аккаунта'),
('Terms of Service', 'ru', 'Условия использования'),
('Privacy Policy', 'ru', 'Политика конфиденциальности'),
('Papers', 'ru', 'Бумажки'),
('engine', 'ru', 'Система'),
('tools', 'ru', 'Инструменты'),
('External', 'ru', 'Внешние'),
('games', 'ru', 'Игры'),
('Legal', 'ru', 'Правовая информация'),
('Array Iterator', 'ru', 'Итератор массива'),
('Data Visualisation', 'ru', 'Визуализация данных'),
('ImageProcessing', 'ru', 'Обработка изображений'),
('Graphs', 'ru', 'Графики'),
('This is graphs', 'ru', 'Это графики')
ON CONFLICT (key, locale) DO NOTHING;

-- Field and filter labels (users, posts, profile, modulerights).
INSERT INTO public.translations (key, locale, value) VALUES
('First Name', 'ru', 'Имя'),
('Last Name', 'ru', 'Фамилия'),
('Avatar URL', 'ru', 'URL аватара'),
('Title', 'ru', 'Заголовок'),
('Author', 'ru', 'Автор'),
('Content', 'ru', 'Содержимое'),
('Email Address', 'ru', 'Адрес эл. почты'),
('Profile Image', 'ru', 'Фото профиля'),
('Groups', 'ru', 'Группы'),
('Allowed Modes', 'ru', 'Разрешённые режимы'),
('Field Access', 'ru', 'Доступ к полям'),
('Public', 'ru', 'Публичный'),
('User Group', 'ru', 'Группа пользователей'),
('Created from', 'ru', 'Создано с'),
('Created to', 'ru', 'Создано по'),
('Administrator', 'ru', 'Администратор'),
('Member', 'ru', 'Участник'),
('Enter a function of x, e.g. Math.sin(x) * 2', 'ru', 'Введите функцию от x, например Math.sin(x) * 2'),
('Add function', 'ru', 'Добавить функцию'),
('Expression did not evaluate to a number', 'ru', 'Выражение не вычислилось в число')
ON CONFLICT (key, locale) DO NOTHING;
