-- 2026.09.10 — comments: one polymorphic discussion table for every module.
-- A comment is attached to a record by (module_id, row_id). The engine also
-- auto-creates these columns from the comments module fieldset; this file pins
-- the types and adds the lookup index.

CREATE TABLE IF NOT EXISTS public.comments (
    id         bigserial   PRIMARY KEY,
    uuid       uuid        NOT NULL DEFAULT uuid_generate_v4(),
    module_id  text        NOT NULL,
    row_id     bigint      NOT NULL,
    body       text        NOT NULL,
    created_by integer,
    created    timestamptz NOT NULL DEFAULT now(),
    updated    timestamptz NOT NULL DEFAULT now(),
    access     integer     NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_comments_target ON public.comments (module_id, row_id);

-- If the table was auto-generated by the engine before its uuid column became a
-- generated UUID, the column can exist with no default. The app never supplies
-- uuid on insert, so backfill NULLs and set the generator default. Idempotent.
-- (fieldTypeToSQL now emits "DEFAULT uuid_generate_v4()" for every TYPE_UUID
-- column, so freshly created tables get this; this fixes pre-existing ones.)
UPDATE public.comments SET uuid = uuid_generate_v4() WHERE uuid IS NULL;
ALTER TABLE public.comments ALTER COLUMN uuid SET DEFAULT uuid_generate_v4();
ALTER TABLE public.comments ALTER COLUMN uuid SET NOT NULL;

-- contact_messages: stored submissions from the site contact form (no email is
-- sent; admins read these through the Contact Messages module). The engine also
-- auto-creates these columns from the module fieldset; this pins the types.
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id         bigserial   PRIMARY KEY,
    uuid       uuid        NOT NULL DEFAULT uuid_generate_v4(),
    name       varchar(120) NOT NULL,
    email      varchar(200) NOT NULL,
    subject    varchar(200),
    message    text        NOT NULL,
    handled    boolean     NOT NULL DEFAULT false,
    created    timestamptz NOT NULL DEFAULT now(),
    updated    timestamptz NOT NULL DEFAULT now(),
    access     integer     NOT NULL DEFAULT 0
);
